security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: root
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: 127.0.0.1
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  context-path: /accounts
  port: 6000
