spring:
  data:
    mongodb:
      host: 127.0.0.1
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  context-path: /uaa
  port: 5000
